### PR TITLE
No error if account has no bookings

### PR DESCRIPTION
**Pull request by luxflux**
This prevents `NoMethodError in Accounts#show: undefined method 'value_date' for nil:NilClass`.

### CODE REVIEW

**Comment by stevschmid** [comment]
:+1:

**Comment by huerlisi** [comment]
Wow, that's old code:-) Remember the days when we had to use `h` to escape everything;-)

I'll merge this as it fixes the issue. This part of code needs some love though to get it up to date and fix the probably related issue in Bookyt: https://github.com/huerlisi/bookyt/issues/71

I'll do a release today or tomorrow. Thanks for the fix!

**Comment by huerlisi** [comment]
I'm working on some more cleanup in this area. Especially to also fix https://github.com/huerlisi/bookyt/issues/71

I try to understand how this issue could show up in the first place. It looks like the only place where we use these partials is in https://github.com/huerlisi/has_accounts_engine/blob/master/app/views/accounts/_show_bookings.html.haml#L17 where we already check for an empty `@bookings` var.

Could you point me to the instances the issue showed up, so I can ensure I won't re-introduce it.

**Comment by luxflux** [comment]
Well, we had the error after we created a new tenant and loaded the `de-CH` seeds in Bookyt.
There is a default account plan created where all of the accounts raised this error.

**Pull request merged**
